# Site settings
title: Vinicius Rezende
email: noisepudding@gmail.com
description: >
  Game Designer
url: "https://vinrzr.github.io" # the base hostname & protocol for your site
linkedin_url: "https://www.linkedin.com/in/vinirez/"
github_username: vinrzr
footer_text: "This site uses <a href='https://github.com/gamingportfolio/urban-theme-portfolio'>urban-theme (portfolio)</a>."

# Build settings
markdown: kramdown
permalink: pretty
